name = "MixedPrecisionIMC"
uuid = "1aba15cf-43f7-482c-a979-1e374f504042"
authors = ["simonbutson <butsons@oregonstate.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
